### ISSUE TITLE
First Demo Issue

### ISSUE THREAD

**Issue by asifhaider** [beyond-the-seas-org/Planning-Presentations#1]
The goal is to get familiar with GitHub issues, projects, and workflows. Issues must be closed after our first discussion meeting regarding the project management via GitHub.

**Comment by asifhaider** [comment]
Done

**Comment by asifhaider** [comment]
There was a mistake. Need to open again!

**Comment by Shahriyar113** [comment]
Understood

**Comment by asifhaider** [comment]
Closing this demo one, as we successfully worked on our actual first issue regarding API design and architecture.
